- name: Fail if Docker version is 17.12.1
  fail:
    msg: "docker_version must be 17.12.1, yours is set to {{ docker_version }}."
  when: docker_version != "17.12.1"

- name: install
  shell: sudo apt-get -y install python python-apt python-pycurl 

- name: judge Docker is intalled
  #shell: "dpkg -l |grep docker |awk '{print $3}' |awk -F [~\t] '{print $1}'"
  shell: "docker --version |awk '{print $3}'|cut -d , -f 1"
  register: result
  ignore_errors: yes

- name: Remove Docker
  when: result.stdout != "{{ docker_version }}-ce"
  apt: name={{ item }} state=absent
  with_items:
    - docker
    - docker-engine
    - docker-ce
    - docker.io

- name: Install dependency soft
  apt: name={{ item }} state=present update_cache=True install_recommends=False
  with_items:
    - python-apt
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add docker apt keys
  shell: "curl -sSL 'https://download.docker.com/linux/ubuntu/gpg'| apt-key add -"

- name: Update apt
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' state=present

- name: Install Docker
  when: result.stdout != "{{ docker_version }}-ce"
  shell: "apt-cache madison docker-ce && apt-get -y install docker-ce=17.12.1~ce-0~ubuntu"

- name: copy docker daemon file
  when: "cluster_network == 'inner_network'"
  template: src=inner_daemon.json dest=/etc/docker/daemon.json

- name: copy docker daemon file
  when: "cluster_network == 'exten_network'"
  template: src=exten_daemon.json dest=/etc/docker/daemon.json

- name: restart docker service
  when: result.stdout != "{{ docker_version }}-ce"
  service: name=docker.service enabled=yes state=restarted
  tags: restart

- name: enable docker service
  shell: systemctl enable docker
  ignore_errors: true

- name: install python-pip
  shell: sudo apt-get -y install python-pip

- name: make directory for docker container
  shell: mkdir -p /home/customer/mysql/data && mkdir -p /home/customer/ayla_adapter_ct/log

- name: Docker-PY
  pip:
    name: "{{ item }}"
  with_items:
  - six==1.11.0
  - docker-py==1.10.6

- name: Add a new docker bridge
  docker_network:
    name: customer
    ipam_options:
      subnet: '172.30.0.0/16'
