- name: Install dependency soft
  shell: yum -y install epel-release

- name: Install python-pip
  yum:
    name: python-pip
    state: present

- name: Install docker-py
  pip:
    name: "{{ item }}"
  with_items:
  - six==1.11.0
  #- docker-py==1.10.6 
  - docker==3.5.0

- name: delete /tmp/ file
  shell: rm -rf /tmp/*
  ignore_errors: true

